apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- moosefs-csi-driverinfo.yaml
- moosefs-csi-rbac.yaml
- moosefs-csi-plugin.yaml

namespace: kube-system
commonLabels:
  app.kubernetes.io/name: moosefs
  app.kubernetes.io/component: csi-plugin
  app.kubernetes.io/managed-by: kubectl-kustomize

images:
- name: MOOSEFS_PLUGIN_IMAGE
  newName: kunde21/moosefs-csi
  newTag: v3.0.112-v0.0.1

generatorOptions:
  # Useful to create a static name for the configmap.
  # Comment this line to create a unique name for the configmap.
  disableNameSuffixHash: true
configMapGenerator:
- name: csi-moosefs-config
  literals:
    # Root path for all volumes created in the cluster
  - MFS_ROOT_PATH="/kubernetes/"
    # IP address or host of the MooseFS master node
  - MFS_SERVER="mfsmaster"
